//@version=5
indicator("for_basic")
sum = 0
for i = 1 to 5
    sum := sum + i
var float __obs_sum = na
__obs_sum := sum

prod = 1
for i = 5 to 1 by -1
    prod := prod * i
var float __obs_prod = na
__obs_prod := prod

countdown = 0
for i = 5 to 1
    countdown := countdown + i
var float __obs_countdown = na
__obs_countdown := countdown

stepVar = 2
total = 0
for i = 0 to 6 by stepVar
    total := total + i
var float __obs_total = na
__obs_total := total

skipsum = 0
for i = 1 to 10
    if i == 4
        continue
    if i == 8
        break
    skipsum := skipsum + i
var float __obs_skipsum = na
__obs_skipsum := skipsum
