
//@version=5
indicator("Multi NS")
var ns = map.new<string, float>()
rsi = nz(ta.rsi(close, 3), 50.0)
map.put(ns, "ta.rsi", rsi)
map.put(ns, "ta.atr", ta.atr(3))
map.put(ns, "price.close", close)
map.put(ns, "price.sma", ta.sma(close, 3))
taRSI = map.get(ns, "ta.rsi", 50.0)
priceSMA = map.get(ns, "price.sma", close)
above = close > priceSMA and taRSI > 50
var float __obs_plot0 = na
__obs_plot0 := above ? 1 : 0
plot(above ? 1 : 0, "Above")
