//@version=5
indicator("Barcode")
var float featureStart = 0.0
var int featureLen = 0
var int maxBarcode = 0
bool aboveMean = close > nz(ta.sma(close, 5), close)
if aboveMean
    if featureLen == 0
        featureStart := close
    featureLen := featureLen + 1
else
    maxBarcode := math.max(maxBarcode, featureLen)
    featureLen := 0
var float __obs_plot0 = na
__obs_plot0 := maxBarcode
plot(maxBarcode, "MaxBarcode")
