
//@version=5
indicator("Multi Acc")
var float cumProfit = 0.0
var float cumLoss = 0.0
var int winStreak = 0
var int loseStreak = 0
ret = nz(close - close[1], 0.0)
if ret > 0
    cumProfit := cumProfit + ret
    winStreak := winStreak + 1
    loseStreak := 0
else if ret < 0
    cumLoss := cumLoss + math.abs(ret)
    loseStreak := loseStreak + 1
    winStreak := 0
profitFactor = cumLoss > 0 ? cumProfit / cumLoss : 0.0
var float __obs_plot0 = na
__obs_plot0 := profitFactor
plot(profitFactor, "PF")
