//@version=5
indicator("Keltner", overlay=true)
length = 10
mult = 1.5
basis = ta.ema(close, length)
atr = ta.atr(length)
upper = basis + mult * atr
lower = basis - mult * atr
squeeze = close > lower and close < upper
var float __obs_plot0 = na
__obs_plot0 := basis
plot(basis)
var float __obs_plot1 = na
__obs_plot1 := upper
plot(upper)
var float __obs_plot2 = na
__obs_plot2 := lower
plot(lower)
var float __obs_plot3 = na
__obs_plot3 := squeeze ? 1.0 : 0.0
plot(squeeze ? 1.0 : 0.0)
