
//@version=5
indicator("All DS")
var float[] arr = array.new_float(0)
var m = map.new<string, float>()
type Info
    float value = 0.0
    int count = 0
var Info info = Info.new()
array.push(arr, close)
if array.size(arr) > 5
    array.shift(arr)
map.put(m, "avg", array.avg(arr))
info.value := map.get(m, "avg", close)
info.count := info.count + 1
var float __obs_plot0 = na
__obs_plot0 := info.value
plot(info.value, "Val")
