
//@version=5
indicator("Enum Regime")
enum Regime
    Trending = 1
    Ranging = 0
    Volatile = 2

atr = ta.atr(3)
avgATR = ta.sma(atr, 5)
sma3 = ta.sma(close, 3)
regime = atr > avgATR * 1.5 ? Regime.Volatile : math.abs(close - sma3) > atr ? Regime.Trending : Regime.Ranging
isTrending = regime == Regime.Trending
var float __obs_plot0 = na
__obs_plot0 := isTrending ? 1 : 0
plot(isTrending ? 1 : 0, "Trend")
