
//@version=5
indicator("Streak")
var int streak = 0
var int maxStreak = 0
isWin = close > open
if isWin
    streak := streak > 0 ? streak + 1 : 1
else
    streak := streak < 0 ? streak - 1 : -1
if math.abs(streak) > maxStreak
    maxStreak := math.abs(streak)
var float __obs_plot0 = na
__obs_plot0 := streak
plot(streak, "Streak")
var float __obs_plot1 = na
__obs_plot1 := maxStreak
plot(maxStreak, "Max")
