
//@version=5
indicator("MA UDT")
type MATracker
    float fastMA = 0.0
    float slowMA = 0.0
    int crossCount = 0

var MATracker mt = MATracker.new()
mt.fastMA := ta.sma(close, 3)
mt.slowMA := ta.sma(close, 5)
if ta.crossover(mt.fastMA, mt.slowMA) or ta.crossunder(mt.fastMA, mt.slowMA)
    mt.crossCount := mt.crossCount + 1
var float __obs_plot0 = na
__obs_plot0 := mt.crossCount
plot(mt.crossCount, "CC")
