
//@version=5
indicator("Trade Logic")
rsi = ta.rsi(close, 3)
sma3 = ta.sma(close, 3)
atr = ta.atr(3)
signal = 0
if close > sma3
    if rsi > 50 and rsi < 70
        if atr > 0
            signal := 3
    else if rsi >= 70
        signal := -1
else
    if rsi < 50 and rsi > 30
        signal := -2
    else if rsi <= 30
        signal := 1
var float __obs_plot0 = na
__obs_plot0 := signal
plot(signal, "Signal")
