//@version=5
indicator("Topo Complexity")
float range1 = high - low
float body = math.abs(close - open)
float upperShadow = high - math.max(close, open)
float lowerShadow = math.min(close, open) - low
int typeCount = 0
typeCount := typeCount + (body > range1 * 0.5 ? 1 : 0)
typeCount := typeCount + (upperShadow > range1 * 0.25 ? 1 : 0)
typeCount := typeCount + (lowerShadow > range1 * 0.25 ? 1 : 0)
var float __obs_plot0 = na
__obs_plot0 := typeCount
plot(typeCount, "TopoComp")
