
//@version=5
indicator("Weighted Rank")
var float[] scores = array.new_float(0)
rsi = ta.rsi(close, 3)
score = nz(rsi, 50.0) / 100.0
array.push(scores, score)
if array.size(scores) > 6
    array.shift(scores)
avgScore = array.avg(scores)
maxScore = array.max(scores)
var float __obs_plot0 = na
__obs_plot0 := avgScore
plot(avgScore, "AvgScore")
var float __obs_plot1 = na
__obs_plot1 := maxScore
plot(maxScore, "MaxScore")
