//@version=5
indicator("EigenCent")
v = array.new_float(3, 1.0)
a01 = math.abs(close - open) < 5.0 ? 1.0 : 0.0
a02 = math.abs(close - high) < 8.0 ? 1.0 : 0.0
a12 = math.abs(open - high) < 8.0 ? 1.0 : 0.0
for iter = 0 to 4
    v0 = array.get(v, 0)
    v1 = array.get(v, 1)
    v2 = array.get(v, 2)
    new0 = a01 * v1 + a02 * v2
    new1 = a01 * v0 + a12 * v2
    new2 = a02 * v0 + a12 * v1
    norm = math.max(math.sqrt(new0 * new0 + new1 * new1 + new2 * new2), 0.001)
    array.set(v, 0, new0 / norm)
    array.set(v, 1, new1 / norm)
    array.set(v, 2, new2 / norm)
topEigen = array.max(v)
var float __obs_plot0 = na
__obs_plot0 := topEigen
plot(topEigen, "TopEig")
