
//@version=5
indicator("All Types")
type AllTypes
    float fVal = 1.5
    int iVal = 10
    bool bVal = true
    string sVal = "test"

var AllTypes at = AllTypes.new()
at.fVal := close
at.iVal := int(nz(ta.rsi(close, 3), 50.0))
at.bVal := close > open
at.sVal := at.bVal ? "up" : "down"
var float __obs_plot0 = na
__obs_plot0 := at.fVal
plot(at.fVal, "F")
var float __obs_plot1 = na
__obs_plot1 := at.iVal
plot(at.iVal, "I")
