
//@version=5
indicator("Reg Enum")
enum RegType
    Trending = 2
    Volatile = 1
    Ranging = 0
    Quiet = -1

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
atr = ta.atr(3)
avgATR = ta.sma(atr, 5)
aligned = (sma3 > sma5 and close > sma3) or (sma3 < sma5 and close < sma3)
highVol = avgATR > 0 and atr > avgATR * 1.3
rtype = aligned and not highVol ? RegType.Trending : highVol ? RegType.Volatile : not aligned and not highVol ? RegType.Quiet : RegType.Ranging
var float __obs_plot0 = na
__obs_plot0 := int(rtype)
plot(int(rtype), "RT")
