
//@version=5
indicator("Stoch Sig")
k = ta.stoch(close, high, low, 5)
d = ta.sma(k, 3)
bullCross = k > d and k[1] <= d[1] and not na(k[1])
bearCross = k < d and k[1] >= d[1] and not na(k[1])
var float __obs_plot0 = na
__obs_plot0 := k
plot(k, "K")
var float __obs_plot1 = na
__obs_plot1 := d
plot(d, "D")
var float __obs_plot2 = na
__obs_plot2 := bullCross ? 1 : bearCross ? -1 : 0
plot(bullCross ? 1 : bearCross ? -1 : 0, "Sig")
