//@version=5
indicator("Volume", overlay=false)
ma_length = input.int(20, title="MA Length")
vol_color = close >= open ? color.green : color.red
var float __obs_plot0 = na
__obs_plot0 := volume
plot(volume, title="Volume", style=plot.style_histogram, color=vol_color)
var float __obs_plot1 = na
__obs_plot1 := ta.sma(volume, ma_length)
plot(ta.sma(volume, ma_length), title="Volume MA", color=color.blue)
