//@version=5
indicator("Competitive Exclusion")
var float sp1 = 100.0
var float sp2 = 100.0
K = 500.0
r1 = 0.06
r2 = 0.04
sp1 := sp1 + r1 * sp1 * (1.0 - (sp1 + sp2 * 0.5) / K)
sp2 := sp2 + r2 * sp2 * (1.0 - (sp2 + sp1 * 0.8) / K)
sp1 := math.max(sp1, 0.0)
sp2 := math.max(sp2, 0.0)
var float __obs_plot0 = na
__obs_plot0 := sp1
plot(sp1, "Species1")
var float __obs_plot1 = na
__obs_plot1 := sp2
plot(sp2, "Species2")
