//@version=5
indicator("CSSpread")
prevHigh = nz(high[1], high)
prevLow = nz(low[1], low)
betaSq = math.pow(math.log(high / low), 2) + math.pow(math.log(prevHigh / prevLow), 2)
twoBarHigh = math.max(high, prevHigh)
twoBarLow = math.min(low, prevLow)
gammaSq = math.pow(math.log(twoBarHigh / twoBarLow), 2)
alpha = (math.sqrt(2.0 * betaSq) - math.sqrt(betaSq)) / (3.0 - 2.0 * math.sqrt(2.0))
spread = alpha > 0 ? 2.0 * (math.exp(alpha) - 1.0) / (1.0 + math.exp(alpha)) : 0.0
var float __obs_plot0 = na
__obs_plot0 := spread
plot(spread, "CSSpr")
