//@version=5
indicator("BB", overlay=true)
length = input.int(20, title="Length")
mult = input.float(2.0, title="StdDev")
ma_type = input.string("SMA", title="Basis MA Type", options=["SMA", "EMA", "WMA"])
src = input.source(close, title="Source")
basis = ma_type == "SMA" ? ta.sma(src, length) : ma_type == "EMA" ? ta.ema(src, length) : ta.wma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
var float __obs_plot0 = na
__obs_plot0 := basis
plot(basis, title="Basis", color=color.blue)
var float __obs_plot1 = na
__obs_plot1 := upper
p1 = plot(upper, title="Upper", color=color.red)
var float __obs_plot2 = na
__obs_plot2 := lower
p2 = plot(lower, title="Lower", color=color.green)
fill(p1, p2, color=color.new(color.blue, 90))
