
//@version=5
indicator("Candle Pat")
type Candle
    float body = 0.0
    float upperWick = 0.0
    float lowerWick = 0.0
    bool bullish = false

var Candle c = Candle.new()
c.body := math.abs(close - open)
c.upperWick := high - math.max(close, open)
c.lowerWick := math.min(close, open) - low
c.bullish := close > open
bodyRatio = high != low ? c.body / (high - low) : 0.5
var float __obs_plot0 = na
__obs_plot0 := bodyRatio
plot(bodyRatio, "BodyRatio")
