
//@version=5
indicator("State Machine")
var state = map.new<string, float>()
var float stateVal = 0.0
map.put(state, "current", stateVal)
rsi = ta.rsi(close, 3)
if stateVal == 0.0
    if rsi > 60
        stateVal := 1.0
else if stateVal == 1.0
    if rsi < 40
        stateVal := 2.0
else
    stateVal := 0.0
map.put(state, "current", stateVal)
var float __obs_plot0 = na
__obs_plot0 := stateVal
plot(stateVal, "State")
