
//@version=5
indicator("Dist Stats")
var float[] returns = array.new_float(0)
ret = close - open
array.push(returns, ret)
if array.size(returns) > 8
    array.shift(returns)
avg = array.avg(returns)
sd = array.stdev(returns)
skew = sd > 0 ? (array.last(returns) - avg) / sd : 0.0
var float __obs_plot0 = na
__obs_plot0 := avg
plot(avg, "Avg")
var float __obs_plot1 = na
__obs_plot1 := skew
plot(skew, "Skew")
