
//@version=5
indicator("MACD Hist Analysis")
[macdLine, sigLine, hist] = ta.macd(close, 3, 5, 3)
histIncreasing = hist > hist[1]
histPositive = hist > 0
var int bullMomentum = 0
if histPositive and histIncreasing
    bullMomentum := bullMomentum + 1
var float __obs_plot0 = na
__obs_plot0 := hist
plot(hist, "Hist")
var float __obs_plot1 = na
__obs_plot1 := bullMomentum
plot(bullMomentum, "BullMom")
