
//@version=5
indicator("DistType")
enum DistShape
    Normal = 0
    LeftSkew = 1
    RightSkew = 2

var float[] data = array.new_float(0)
array.push(data, close)
if array.size(data) > 5
    array.shift(data)
mean = array.avg(data)
sorted = array.copy(data)
array.sort(sorted, order.ascending)
sz = array.size(sorted)
midIdx = math.floor(float(sz) / 2.0)
median = array.get(sorted, int(midIdx))
shape = mean > median + 0.5 ? DistShape.RightSkew : mean < median - 0.5 ? DistShape.LeftSkew : DistShape.Normal
var float __obs_plot0 = na
__obs_plot0 := int(shape)
plot(int(shape), "DS")
