//@version=5
indicator("TitForTat")
var int myAction = 1
var int oppAction = 1
var float myScore = 0.0
oppAction := close > nz(close[1], close) ? 1 : 0
if myAction == 1 and oppAction == 1
    myScore := myScore + 3.0
else if myAction == 1 and oppAction == 0
    myScore := myScore + 0.0
else if myAction == 0 and oppAction == 1
    myScore := myScore + 5.0
else
    myScore := myScore + 1.0
myAction := oppAction
var float __obs_plot0 = na
__obs_plot0 := myScore
plot(myScore, "Score")
var float __obs_plot1 = na
__obs_plot1 := float(myAction)
plot(float(myAction), "Act")
