//@version=5
indicator("SuperTrend")
factor = 2.0
atrPeriod = 3
src = (high + low) / 2

atr_ = ta.atr(atrPeriod)
var float upperBand = 0.0
var float lowerBand = 0.0
var int direction = 1

ub = src + factor * nz(atr_)
lb = src - factor * nz(atr_)

lowerBand := lb > lowerBand or close[1] < lowerBand ? lb : lowerBand
upperBand := ub < upperBand or close[1] > upperBand ? ub : upperBand

if close > upperBand
    direction := 1
if close < lowerBand
    direction := -1

var float superTrend = 0.0
superTrend := direction == 1 ? lowerBand : upperBand
var float __obs_plot0 = na
__obs_plot0 := close
plot(close)
