//@version=5
indicator("ShortPath")
dAB = math.abs(close - open)
dBC = math.abs(open - (high + low) / 2.0)
dAC = math.abs(close - (high + low) / 2.0)
directAC = dAC
indirectAC = dAB + dBC
shortest = math.min(directAC, indirectAC)
usedDirect = directAC <= indirectAC ? 1.0 : 0.0
var float __obs_plot0 = na
__obs_plot0 := shortest
plot(shortest, "ShortAC")
var float __obs_plot1 = na
__obs_plot1 := usedDirect
plot(usedDirect, "Direct")
