//@version=5
indicator("Vickrey")
bids = array.new_float(0)
array.push(bids, close * 0.98)
array.push(bids, close * 1.01)
array.push(bids, close * 0.99)
array.push(bids, close * 1.02)
array.sort(bids, order.descending)
winBid = array.get(bids, 0)
pricePaid = array.get(bids, 1)
surplus = winBid - pricePaid
var float __obs_plot0 = na
__obs_plot0 := pricePaid
plot(pricePaid, "Price")
var float __obs_plot1 = na
__obs_plot1 := surplus
plot(surplus, "Surplus")
