//@version=5
indicator("MACD Hist Color")
fast = 12
slow = 26
signal_len = 9
[macdLine, signalLine, hist] = ta.macd(close, fast, slow, signal_len)
isGrowing = hist > nz(hist[1], 0)
isPositive = hist >= 0
c = isPositive ?
    (isGrowing ? color.green : color.lime) :
    (isGrowing ? color.orange : color.red)
var float __obs_plot0 = na
__obs_plot0 := hist
plot(hist, color=c, style=plot.style_histogram)
var float __obs_plot1 = na
__obs_plot1 := macdLine
plot(macdLine)
var float __obs_plot2 = na
__obs_plot2 := signalLine
plot(signalLine)
