//@version=5
indicator("Diffusion Array")
var float[] increments = array.new_float(0)
float prevC = not na(close[1]) ? close[1] : close
float inc = close - prevC
if array.size(increments) >= 5
    array.shift(increments)
array.push(increments, inc)
float avgInc = array.size(increments) > 0 ?
    array.get(increments, 0) : 0.0
var float __obs_plot0 = na
__obs_plot0 := avgInc
plot(avgInc, "AvgInc")
