
//@version=5
indicator("Cross Var")
var int lastCrossBar = 0
var int crossCount = 0
ema3 = ta.ema(close, 3)
sma5 = ta.sma(close, 5)
var int barNum = 0
barNum := barNum + 1
if ta.crossover(ema3, sma5)
    crossCount := crossCount + 1
    lastCrossBar := barNum
barsSinceCross = barNum - lastCrossBar
var float __obs_plot0 = na
__obs_plot0 := crossCount
plot(crossCount, "Cnt")
var float __obs_plot1 = na
__obs_plot1 := barsSinceCross
plot(barsSinceCross, "BSC")
