
//@version=5
indicator("Map Filter")
var scores = map.new<string, float>()
map.put(scores, "rsi", nz(ta.rsi(close, 3), 50.0))
map.put(scores, "cci", nz(ta.cci(close, 5), 0.0))
map.put(scores, "mfi", nz(ta.mfi(close, 5), 50.0))
aboveThreshold = 0
for [k, v] in scores
    if v > 50
        aboveThreshold := aboveThreshold + 1
var float __obs_plot0 = na
__obs_plot0 := aboveThreshold
plot(aboveThreshold, "Above50")
