
//@version=5
indicator("Trend Duration")
sma3 = ta.sma(close, 3)
var int upDuration = 0
var int downDuration = 0
if close > sma3
    upDuration := upDuration + 1
    downDuration := 0
else
    downDuration := downDuration + 1
    upDuration := 0
longestUp = math.max(upDuration, upDuration[1])
var float __obs_plot0 = na
__obs_plot0 := upDuration
plot(upDuration, "UpDur")
var float __obs_plot1 = na
__obs_plot1 := downDuration
plot(downDuration, "DownDur")
