
//@version=5
indicator("Dist Met")
var dm = map.new<string, float>()
var float[] data = array.new_float(0)
array.push(data, close)
if array.size(data) > 8
    array.shift(data)
map.put(dm, "mean", array.avg(data))
map.put(dm, "min", array.min(data))
map.put(dm, "max", array.max(data))
map.put(dm, "range", array.max(data) - array.min(data))
rng = map.get(dm, "range", 0.0)
var float __obs_plot0 = na
__obs_plot0 := rng
plot(rng, "Range")
