//@version=5
indicator("Elitism")
var float bestFitness = 0.0
var float bestGene = 0.0
currentFitness = math.abs(close - 105.0)
inverseFit = 1.0 / math.max(currentFitness, 0.01)
if inverseFit > bestFitness
    bestFitness := inverseFit
    bestGene := close
var float __obs_plot0 = na
__obs_plot0 := bestGene
plot(bestGene, "Elite")
var float __obs_plot1 = na
__obs_plot1 := bestFitness
plot(bestFitness, "Fit")
