
//@version=5
indicator("Cross Div")
sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
rsi = nz(ta.rsi(close, 3), 50.0)
maCrossUp = ta.crossover(sma3, sma5)
maCrossDn = ta.crossunder(sma3, sma5)
rsiDivUp = rsi > 50 and close < sma5
rsiDivDn = rsi < 50 and close > sma5
signal = maCrossUp ? 2 : maCrossDn ? -2 : rsiDivUp ? 1 : rsiDivDn ? -1 : 0
var float __obs_plot0 = na
__obs_plot0 := signal
plot(signal, "Sig")
