
//@version=5
indicator("Var ForIn")
var cumScore = map.new<string, float>()
rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
map.put(cumScore, "rsi", map.get(cumScore, "rsi", 0.0) + (rsi > 50 ? 1.0 : -1.0))
map.put(cumScore, "trend", map.get(cumScore, "trend", 0.0) + (close > sma3 ? 1.0 : -1.0))
total = 0.0
for [k, v] in cumScore
    total := total + v
var float __obs_plot0 = na
__obs_plot0 := total
plot(total, "Tot")
