
//@version=5
indicator("OBV Ext")
var float obv = 0.0
if close > close[1] and not na(close[1])
    obv := obv + volume
else if close < close[1] and not na(close[1])
    obv := obv - volume
obvMA = ta.sma(obv, 3)
diverging = (close > close[1] and obv < obv[1]) or (close < close[1] and obv > obv[1])
var float __obs_plot0 = na
__obs_plot0 := obv
plot(obv, "OBV")
var float __obs_plot1 = na
__obs_plot1 := diverging ? 1 : 0
plot(diverging ? 1 : 0, "Div")
