//@version=5
indicator("StarHub")
hub = close
leaves = array.new_float(0)
array.push(leaves, open)
array.push(leaves, high)
array.push(leaves, low)
array.push(leaves, (high + low) / 2.0)
hubDeg = 0.0
thresh = 7.0
for i = 0 to 3
    leaf = array.get(leaves, i)
    if math.abs(hub - leaf) < thresh
        hubDeg := hubDeg + 1.0
hubScore = hubDeg / 4.0
var float __obs_plot0 = na
__obs_plot0 := hubScore
plot(hubScore, "HubScore")
