//@version=5
indicator("Stochastic", overlay=false)
periodK = input.int(14, title="%K Length")
smoothK = input.int(1, title="%K Smoothing")
periodD = input.int(3, title="%D Smoothing")
k = ta.sma(ta.stoch(close, high, low, periodK), smoothK)
d = ta.sma(k, periodD)
var float __obs_plot0 = na
__obs_plot0 := k
plot(k, title="%K", color=color.blue)
var float __obs_plot1 = na
__obs_plot1 := d
plot(d, title="%D", color=color.red)
hline(80, title="Upper Band")
hline(20, title="Lower Band")
