
//@version=5
indicator("Alert Conds")
var alerts = map.new<string, float>()
rsi = ta.rsi(close, 3)
sma3 = ta.sma(close, 3)
map.put(alerts, "rsi_ob", rsi > 70 ? 1.0 : 0.0)
map.put(alerts, "rsi_os", rsi < 30 ? 1.0 : 0.0)
map.put(alerts, "above_ma", close > sma3 ? 1.0 : 0.0)
activeAlerts = map.get(alerts, "rsi_ob", 0.0) + map.get(alerts, "rsi_os", 0.0) + map.get(alerts, "above_ma", 0.0)
var float __obs_plot0 = na
__obs_plot0 := activeAlerts
plot(activeAlerts, "Active")
