
//@version=5
indicator("Plot Colors")
sma3 = ta.sma(close, 3)
rsi = ta.rsi(close, 3)
trend = close > sma3
trendColor = trend ? color.green : color.red
rsiColor = rsi > 70 ? color.red : rsi < 30 ? color.green : color.gray
var float __obs_plot0 = na
__obs_plot0 := sma3
plot(sma3, "SMA", color=trendColor)
var float __obs_plot1 = na
__obs_plot1 := rsi
plot(rsi, "RSI", color=rsiColor)
bgcolor(color.new(trendColor, 90))
hline(50, "Mid")
