
//@version=5
indicator("Pivot Det")
isHighPivot = true
isLowPivot = true
midHigh = high[2]
midLow = low[2]
for i = 0 to 4
    if i != 2
        h = high[i]
        l = low[i]
        if not na(h) and not na(midHigh) and h >= midHigh
            isHighPivot := false
        if not na(l) and not na(midLow) and l <= midLow
            isLowPivot := false
var float __obs_plot0 = na
__obs_plot0 := isHighPivot ? 1 : 0
plot(isHighPivot ? 1 : 0, "HighPivot")
var float __obs_plot1 = na
__obs_plot1 := isLowPivot ? 1 : 0
plot(isLowPivot ? 1 : 0, "LowPivot")
