
//@version=5
indicator("Swing")
var float lastSwingHi = 0.0
var float lastSwingLo = 99999.0
isSwingHi = not na(high[2]) and high[1] > high[2] and high[1] > high
isSwingLo = not na(low[2]) and low[1] < low[2] and low[1] < low
if isSwingHi
    lastSwingHi := high[1]
if isSwingLo
    lastSwingLo := low[1]
var float __obs_plot0 = na
__obs_plot0 := lastSwingHi
plot(lastSwingHi, "SH")
var float __obs_plot1 = na
__obs_plot1 := lastSwingLo
plot(lastSwingLo, "SL")
