
//@version=5
indicator("State Trans")
enum MarketState
    Trending = 1
    Ranging = 0
    Volatile = 2

atrVal = ta.atr(3)
smaATR = ta.sma(atrVal, 5)
sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)

currentState = atrVal > smaATR * 1.5 ? MarketState.Volatile : math.abs(sma3 - sma5) > atrVal ? MarketState.Trending : MarketState.Ranging
var float __obs_plot0 = na
__obs_plot0 := int(currentState)
plot(int(currentState), "State")
