
//@version=5
indicator("UDT Reassign")
type Level
    float price = 0.0
    int bar = 0

var Level support = Level.new(close, 0)
var Level resistance = Level.new(close, 0)
if close < support.price
    support := Level.new(close, bar_index)
if close > resistance.price
    resistance := Level.new(close, bar_index)
channel = resistance.price - support.price
var float __obs_plot0 = na
__obs_plot0 := channel
plot(channel, "Channel")
