//@version=5
indicator("Cross")
fast = ta.ema(close, 3)
slow = ta.ema(close, 5)
var int cross_up_count = 0
var int cross_dn_count = 0
if ta.crossover(fast, slow)
    cross_up_count := cross_up_count + 1
if ta.crossunder(fast, slow)
    cross_dn_count := cross_dn_count + 1
var float result = 0.0
result := cross_up_count + cross_dn_count
var float __obs_plot0 = na
__obs_plot0 := result
plot(result)
