//@version=5
indicator("WhileEst18")
var float est = 0.5
target = close > open ? 1.0 : 0.0
iter = 0
tempEst = est
while math.abs(tempEst - target) > 0.1 and iter < 10
    tempEst := tempEst + 0.15 * (target - tempEst)
    iter := iter + 1
est := tempEst
selfInfo = est > 0.01 and est < 0.99 ? -(est * math.log(est) + (1.0 - est) * math.log(1.0 - est)) : 0.0
var float __obs_plot0 = na
__obs_plot0 := selfInfo
plot(selfInfo, "si")
