
//@version=5
indicator("Ichimoku")
conversionPeriod = 3
basePeriod = 5
conversion = (ta.highest(high, conversionPeriod) + ta.lowest(low, conversionPeriod)) / 2.0
base = (ta.highest(high, basePeriod) + ta.lowest(low, basePeriod)) / 2.0
bullish = close > conversion and conversion > base
var float __obs_plot0 = na
__obs_plot0 := conversion
plot(conversion, "Conversion")
var float __obs_plot1 = na
__obs_plot1 := base
plot(base, "Base")
var float __obs_plot2 = na
__obs_plot2 := bullish ? 1 : 0
plot(bullish ? 1 : 0, "Bull")
