
//@version=5
indicator("RSI Bands")
rsi = nz(ta.rsi(close, 3), 50.0)
rsiMA = ta.sma(rsi, 5)
rsiSD = ta.stdev(rsi, 5)
upperBand = rsiMA + rsiSD * 2
lowerBand = rsiMA - rsiSD * 2
overbought = rsi > upperBand
oversold = rsi < lowerBand
var float __obs_plot0 = na
__obs_plot0 := rsi
plot(rsi, "RSI")
var float __obs_plot1 = na
__obs_plot1 := overbought ? 1 : oversold ? -1 : 0
plot(overbought ? 1 : oversold ? -1 : 0, "Sig")
