
//@version=5
indicator("Deque")
var float[] dq = array.new_float(0)
if close > open
    array.push(dq, close)
else
    array.unshift(dq, close)
if array.size(dq) > 6
    if close > open
        array.shift(dq)
    else
        array.pop(dq)
var float __obs_plot0 = na
__obs_plot0 := array.size(dq)
plot(array.size(dq), "Size")
var float __obs_plot1 = na
__obs_plot1 := array.avg(dq)
plot(array.avg(dq), "Avg")
