//@version=5
indicator("CausalImpact")
var float cumImpact = 0.0
var float baseline = 0.0
var int preCnt = 0
cutoff = 4
if bar_index < cutoff
    preCnt := preCnt + 1
    baseline := baseline + (close - baseline) / float(preCnt)
else
    deviation = close - baseline
    cumImpact := cumImpact + deviation
var float __obs_plot0 = na
__obs_plot0 := cumImpact
plot(cumImpact, "CumImpact")
var float __obs_plot1 = na
__obs_plot1 := baseline
plot(baseline, "Baseline")
