
//@version=5
indicator("Dbl Exp")
var float level = 0.0
var float trend = 0.0
var bool init = false
alpha = 0.4
beta = 0.3
if not init
    level := close
    trend := 0.0
    init := true
else
    prevLevel = level
    level := alpha * close + (1 - alpha) * (level + trend)
    trend := beta * (level - prevLevel) + (1 - beta) * trend
forecast = level + trend
var float __obs_plot0 = na
__obs_plot0 := forecast
plot(forecast, "Fcst")
