
//@version=5
indicator("Enum Str")
enum Phase
    Accumulation = 1
    Markup = 2
    Distribution = 3
    Markdown = 4

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
rsi = nz(ta.rsi(close, 3), 50.0)
phase = close > sma3 and rsi < 50 ? Phase.Accumulation : close > sma3 and rsi > 50 ? Phase.Markup : close < sma3 and rsi > 50 ? Phase.Distribution : Phase.Markdown
isBullPhase = phase == Phase.Accumulation or phase == Phase.Markup
var float __obs_plot0 = na
__obs_plot0 := isBullPhase ? 1 : 0
plot(isBullPhase ? 1 : 0, "Bull")
