
//@version=5
indicator("Regime Dur")
var int currentRegime = 0
var int duration = 0
sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
newRegime = sma3 > sma5 ? 1 : -1
if newRegime != currentRegime
    currentRegime := newRegime
    duration := 1
else
    duration := duration + 1
var float __obs_plot0 = na
__obs_plot0 := duration
plot(duration, "Dur")
var float __obs_plot1 = na
__obs_plot1 := currentRegime
plot(currentRegime, "Reg")
