//@version=5
indicator("MixedStrat")
a11 = close - open
a12 = high - close
a21 = close - low
a22 = high - low
denom = (a11 - a12 - a21 + a22)
probP1 = math.abs(denom) > 0.01 ? (a22 - a21) / denom : 0.5
probP1 := math.max(0.0, math.min(1.0, probP1))
probP2 = math.abs(denom) > 0.01 ? (a22 - a12) / denom : 0.5
probP2 := math.max(0.0, math.min(1.0, probP2))
plot(probP1, "P1Mix")
plot(probP2, "P2Mix")
