//@version=5
strategy("C300-18")
var float entryPrice = 0.0
atrVal = nz(ta.atr(3), 1.0)
if strategy.position_size == 0
    if close > open
        strategy.entry("Long", strategy.long)
        entryPrice := close
if strategy.position_size > 0
    stopLevel = entryPrice - 2.0 * atrVal
    tpLevel = entryPrice + 3.0 * atrVal
    if close < stopLevel or close > tpLevel
        strategy.close("Long")
