
//@version=5
indicator("UDT Method")
type Indicator
    float value = 0.0
    float prev = 0.0
    bool rising = false

updateInd(Indicator ind, float newVal) =>
    ind.prev := ind.value
    ind.value := newVal
    ind.rising := newVal > ind.prev

var Indicator rsiInd = Indicator.new()
rsi = nz(ta.rsi(close, 3), 50.0)
updateInd(rsiInd, rsi)
plot(rsiInd.value, "Val")
plot(rsiInd.rising ? 1 : 0, "Rise")
