//@version=5
indicator("Hazard Ratio")
var int bullEvents = 0
var int bearEvents = 0
var int bullTime = 0
var int bearTime = 0
bool bull = close > open
if bull
    bullTime := bullTime + 1
    bullEvents := bullEvents + (volume > 1200 ? 1 : 0)
else
    bearTime := bearTime + 1
    bearEvents := bearEvents + (volume > 1200 ? 1 : 0)
float bullRate = bullTime > 0 ? bullEvents / bullTime : 0.0
float bearRate = bearTime > 0 ? bearEvents / bearTime : 0.0
float hr = bearRate > 0.0 ? bullRate / bearRate : 1.0
plot(hr, "HazardRatio")
