
//@version=5
indicator("Sig Str")
enum SigStr
    VeryStrong = 3
    Strong = 2
    Moderate = 1
    Weak = 0

rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
volUp = volume > ta.sma(volume, 5)
score = (close > sma3 ? 1 : 0) + (rsi > 55 ? 1 : 0) + (volUp ? 1 : 0)
ss = switch score
    3 => SigStr.VeryStrong
    2 => SigStr.Strong
    1 => SigStr.Moderate
    => SigStr.Weak
plot(int(ss), "SS")
