
//@version=5
indicator("Enum Switch Full")
enum Market
    StrongBull = 3
    Bull = 2
    Neutral = 1
    Bear = 0
    StrongBear = -1

rsi = ta.rsi(close, 3)
sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)

market = rsi > 70 and sma3 > sma5 ? Market.StrongBull :
     rsi > 50 and close > sma3 ? Market.Bull :
     rsi < 30 and sma3 < sma5 ? Market.StrongBear :
     rsi < 50 and close < sma3 ? Market.Bear :
     Market.Neutral

action = switch market
    Market.StrongBull => 2.0
    Market.Bull => 1.0
    Market.StrongBear => -2.0
    Market.Bear => -1.0
    => 0.0
plot(action, "Action")
