
//@version=5
indicator("Nested CF")
rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
atr = ta.atr(3)
result = 0
if close > sma3
    if rsi > 55
        for i = 0 to 2
            if close[i] > sma3[i] and not na(close[i]) and not na(sma3[i])
                result := result + 1
    else
        result := -1
else
    if rsi < 45
        result := -2
    else
        result := 0
plot(result, "Res")
