
//@version=5
indicator("Enum Full")
enum Action
    StrongBuy = 4
    Buy = 3
    Hold = 2
    Sell = 1
    StrongSell = 0

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
rsi = nz(ta.rsi(close, 3), 50.0)
score = (close > sma3 ? 1 : 0) + (sma3 > sma5 ? 1 : 0) + (rsi > 55 ? 1 : 0) + (volume > ta.sma(volume, 5) ? 1 : 0)
action = switch score
    4 => Action.StrongBuy
    3 => Action.Buy
    2 => Action.Hold
    1 => Action.Sell
    => Action.StrongSell
plot(int(action), "A")
