//@version=5
strategy("BayesStrat")
var float alphaUp = 1.0
var float betaDn = 1.0
var int pos = 0
isUp = close > nz(close[1], close) ? 1.0 : 0.0
alphaUp := alphaUp + isUp
betaDn := betaDn + (1.0 - isUp)
postProbUp = alphaUp / (alphaUp + betaDn)
if postProbUp > 0.65 and pos == 0
    strategy.entry("BayesL", strategy.long)
    pos := 1
else if postProbUp < 0.4 and pos == 1
    strategy.close("BayesL")
    pos := 0
plot(postProbUp, "PostUp")
