//@version=5
indicator("MA Dispatch")
maType = input.string("EMA", title="MA Type")
maLength = input.int(5, title="Length")
ma = switch maType
    "EMA" => ta.ema(close, maLength)
    "SMA" => ta.sma(close, maLength)
    "RMA" => ta.rma(close, maLength)
    "WMA" => ta.wma(close, maLength)
    =>
        runtime.error("No matching MA type")
        float(na)
var float last_ma = 0.0
last_ma := nz(ma)
plot(close)
