
//@version=5
indicator("Map Keys")
var indicators = map.new<string, float>()
map.put(indicators, "rsi", nz(ta.rsi(close, 3), 50.0))
map.put(indicators, "cci", nz(ta.cci(close, 5), 0.0))
map.put(indicators, "stoch", ta.stoch(close, high, low, 5))
aboveNeutral = 0
for [k, v] in indicators
    if k == "cci"
        if v > 0
            aboveNeutral := aboveNeutral + 1
    else
        if v > 50
            aboveNeutral := aboveNeutral + 1
plot(aboveNeutral, "Above")
