
//@version=5
indicator("Sig Hist")
var hist = map.new<string, float>()
rsi = ta.rsi(close, 3)
sma3 = ta.sma(close, 3)
currentSig = close > sma3 and rsi > 50 ? 1.0 : -1.0
map.put(hist, "t_2", map.get(hist, "t_1", 0.0))
map.put(hist, "t_1", map.get(hist, "t_0", 0.0))
map.put(hist, "t_0", currentSig)
consistent = map.get(hist, "t_0", 0.0) == map.get(hist, "t_1", 0.0) and map.get(hist, "t_1", 0.0) == map.get(hist, "t_2", 0.0)
plot(consistent ? 1 : 0, "Consistent")
