
//@version=5
indicator("Risk Prof")
enum RiskProf
    Conservative = 0
    Balanced = 1
    Growth = 2
    Aggressive = 3

rsi = nz(ta.rsi(close, 3), 50.0)
atr = nz(ta.atr(3), 1.0)
avgATR = ta.sma(nz(ta.atr(3), 1.0), 5)
volLow = avgATR > 0 ? atr / avgATR < 0.8 : false
rp = switch
    rsi > 60 and volLow => RiskProf.Aggressive
    rsi > 50 => RiskProf.Growth
    rsi > 40 => RiskProf.Balanced
    => RiskProf.Conservative
plot(int(rp), "RP")
