
//@version=5
indicator("Pct Anal")
var float[] data = array.new_float(0)
array.push(data, close)
if array.size(data) > 8
    array.shift(data)
sorted = array.copy(data)
array.sort(sorted)
p25 = array.percentile_linear_interpolation(sorted, 25.0)
p75 = array.percentile_linear_interpolation(sorted, 75.0)
iqr = p75 - p25
isOutlier = close > p75 + 1.5 * iqr or close < p25 - 1.5 * iqr
plot(isOutlier ? 1 : 0, "Out")
