
//@version=5
indicator("Trade Track")
var int trades = 0
var float cumPnL = 0.0
var bool inTrade = false
sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
var float entryPrice = 0.0
if not inTrade and sma3 > sma5
    inTrade := true
    entryPrice := close
    trades := trades + 1
if inTrade and sma3 < sma5
    pnl = close - entryPrice
    cumPnL := cumPnL + pnl
    inTrade := false
plot(cumPnL, "PnL")
