//@version=5
indicator("Supertrend UDF Full")
pine_supertrend(float factor, int atrPeriod) =>
    src = (high + low) / 2
    atr = ta.atr(atrPeriod)
    upper = src + factor * atr
    lower = src - factor * atr
    direction = close > upper ? -1 : close < lower ? 1 : 0
    st = direction == -1 ? lower : upper
    [st, direction]
[supertrend, direction] = pine_supertrend(3.0, 10)
plot(supertrend)
plot(direction)
