//@version=5
indicator("Comprehensive C98")
type Signal
    float value = 0.0
    int direction = 0
var float result = 0.0
lbl = label.new(bar_index, close)
getSignal(src, len) =>
    sma = ta.sma(src, len)
    if src > sma
        Signal.new(src - sma, 1)
    else
        Signal.new(sma - src, -1)
sig = getSignal(close, 5)
arr = array.new_float(0)
arr.push(sig.value)
result := sig.direction > 0 ? sig.value : -sig.value
