//@version=5
strategy("test", overlay=true)
longCondition = close > open
shortCondition = close < open
scenario = "market"
switch scenario
    "market" =>
        if longCondition
            strategy.entry("long", strategy.long)
        if shortCondition
            strategy.entry("short", strategy.short)
    "limit" =>
        if longCondition
            strategy.entry("long_lim", strategy.long)
