
//@version=5
indicator("Stat Qual E")
enum StatQual
    Excellent = 3
    Good = 2
    Fair = 1
    Poor = 0

ret = close[1] > 0 ? (close - close[1]) / close[1] * 100 : 0.0
avgRet = ta.sma(ret, 5)
retDev = ta.stdev(ret, 5)
sharpe = retDev > 0 ? avgRet / retDev : 0.0
sq = switch
    sharpe > 2 => StatQual.Excellent
    sharpe > 1 => StatQual.Good
    sharpe > 0 => StatQual.Fair
    => StatQual.Poor
plot(int(sq), "SQ")
