
//@version=5
indicator("OF UDT")
type OrderFlow
    float buyPressure = 0.0
    float sellPressure = 0.0
    float delta = 0.0

var OrderFlow of = OrderFlow.new()
buyVol = close > open ? volume : volume * 0.4
sellVol = close < open ? volume : volume * 0.4
of.buyPressure := ta.sma(buyVol, 3)
of.sellPressure := ta.sma(sellVol, 3)
of.delta := of.buyPressure - of.sellPressure
plot(of.delta, "Delta")
