
//@version=5
indicator("Trend Type")
enum TType
    StrongUp = 2
    WeakUp = 1
    Flat = 0
    WeakDown = -1
    StrongDown = -2

sma3 = ta.sma(close, 3)
atr = ta.atr(3)
dist = close - sma3
normDist = atr > 0 ? dist / atr : 0.0
ttype = normDist > 2 ? TType.StrongUp : normDist > 0.5 ? TType.WeakUp : normDist < -2 ? TType.StrongDown : normDist < -0.5 ? TType.WeakDown : TType.Flat
plot(int(ttype), "TT")
