
//@version=5
indicator("Mom Level E")
enum MomLevel
    VeryStrong = 2
    Strong = 1
    Neutral = 0
    Weak = -1
    VeryWeak = -2

rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
ml = switch
    rsi > 70 and close > sma3 => MomLevel.VeryStrong
    rsi > 55 => MomLevel.Strong
    rsi < 30 and close < sma3 => MomLevel.VeryWeak
    rsi < 45 => MomLevel.Weak
    => MomLevel.Neutral
plot(int(ml), "ML")
