//@version=5
indicator("DG-11 Parallel Transport")
var float vecX = 1.0
var float vecY = 0.0
if not na(close[2])
    dp1 = close - close[1]
    dp0 = close[1] - close[2]
    dTheta = 0.0
    mag0 = math.sqrt(1.0 + dp0 * dp0)
    mag1 = math.sqrt(1.0 + dp1 * dp1)
    cosA = (1.0 + dp0 * dp1) / (mag0 * mag1)
    cosA := math.max(math.min(cosA, 1.0), -1.0)
    dTheta := math.acos(cosA)
    newX = vecX * math.cos(dTheta) - vecY * math.sin(dTheta)
    newY = vecX * math.sin(dTheta) + vecY * math.cos(dTheta)
    vecX := newX
    vecY := newY
plot(vecX)
