
//@version=5
indicator("UDT Map")
type Indicators
    float rsi = 50.0
    float macd = 0.0
    float atr = 0.0
    float sma = 0.0

var Indicators ind = Indicators.new()
ind.rsi := nz(ta.rsi(close, 3), 50.0)
[m, s, h] = ta.macd(close, 3, 5, 3)
ind.macd := h
ind.atr := ta.atr(3)
ind.sma := ta.sma(close, 3)
bullCount = (ind.rsi > 50 ? 1 : 0) + (ind.macd > 0 ? 1 : 0) + (close > ind.sma ? 1 : 0)
plot(bullCount, "Bull")
