
//@version=5
indicator("Cond Sum")
var indicators = map.new<string, float>()
map.put(indicators, "rsi", nz(ta.rsi(close, 3), 50.0))
map.put(indicators, "mfi", nz(ta.mfi(close, 5), 50.0))
map.put(indicators, "cci", nz(ta.cci(close, 5), 0.0))
bullScore = 0.0
for [k, v] in indicators
    if k == "cci"
        bullScore := bullScore + (v > 0 ? 1.0 : 0.0)
    else
        bullScore := bullScore + (v > 50 ? 1.0 : 0.0)
plot(bullScore, "Bull")
