//@version=5
indicator("Squeeze Mom")
length = 20
multKC = 1.5
basis = ta.sma(close, length)
dev = multKC * ta.stdev(close, length)
upperBB = basis + dev
lowerBB = basis - dev
upperKC = basis + multKC * ta.atr(length)
lowerKC = basis - multKC * ta.atr(length)
sqzOn = lowerBB > lowerKC and upperBB < upperKC
sqzOff = lowerBB < lowerKC and upperBB > upperKC
val = ta.linreg(close - math.avg(math.avg(ta.highest(high, length), ta.lowest(low, length)), ta.sma(close, length)), length, 0)
plot(val)
