//@version=5
indicator("Rule Classification")
var ruleClasses = map.new<string, int>()
map.put(ruleClasses, "rule30", 3)
map.put(ruleClasses, "rule90", 2)
map.put(ruleClasses, "rule110", 4)
map.put(ruleClasses, "rule184", 2)
var int curClass = 0
rsiVal = nz(ta.rsi(close, 3), 50.0)
selectedRule = rsiVal > 60 ? "rule110" : rsiVal > 40 ? "rule30" : "rule90"
curClass := map.get(ruleClasses, selectedRule)
