
//@version=5
indicator("Level UDT")
type LevelTracker
    float resistance = 0.0
    float support = 99999.0
    int testCount = 0

var LevelTracker lt = LevelTracker.new()
lt.resistance := math.max(lt.resistance, high)
lt.support := math.min(lt.support, low)
atr = nz(ta.atr(3), 1.0)
nearRes = math.abs(close - lt.resistance) < atr
if nearRes
    lt.testCount := lt.testCount + 1
plot(lt.testCount, "TC")
