//@version=5
indicator("ChowTest")
var float ssePre = 0.0
var float ssePost = 0.0
var float preMean = 0.0
var float postMean = 0.0
var int preCnt = 0
var int postCnt = 0
cutoff = 5
if bar_index < cutoff
    preCnt := preCnt + 1
    preMean := preMean + (close - preMean) / float(preCnt)
    ssePre := ssePre + math.pow(close - preMean, 2)
else
    postCnt := postCnt + 1
    postMean := postMean + (close - postMean) / float(postCnt)
    ssePost := ssePost + math.pow(close - postMean, 2)
totalSSE = ssePre + ssePost
plot(totalSSE, "SSE")
plot(preMean, "PreMu")
plot(postMean, "PostMu")
