//@version=5
indicator("UDT TA")
type Indicator
    float smaVal = 0.0
    float emaVal = 0.0
    float rsiVal = 0.0
    string signal = "none"
ind = Indicator.new()
sma5 = ta.sma(close, 5)
ema5 = ta.ema(close, 5)
rsi5 = ta.rsi(close, 5)
if not na(sma5)
    ind.smaVal := sma5
if not na(ema5)
    ind.emaVal := ema5
if not na(rsi5)
    ind.rsiVal := rsi5
    ind.signal := rsi5 > 70 ? "OB" : rsi5 < 30 ? "OS" : "neutral"
