
//@version=5
strategy("Data Strat", overlay=true)
var float[] signals = array.new_float(0)
rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
sig = (rsi > 50 ? 1.0 : -1.0) + (close > sma3 ? 1.0 : -1.0)
array.push(signals, sig)
if array.size(signals) > 3
    array.shift(signals)
avgSig = array.avg(signals)
if avgSig > 1.0
    strategy.entry("Long", strategy.long)
if avgSig < 0
    strategy.close("Long")
plot(sma3, "MA")
