
//@version=5
strategy("Enum Strat", overlay=true)
enum Regime
    Bull = 1
    Bear = -1
    Neutral = 0

rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
regime = close > sma3 and rsi > 55 ? Regime.Bull : close < sma3 and rsi < 45 ? Regime.Bear : Regime.Neutral
action = switch regime
    Regime.Bull => 1
    Regime.Bear => -1
    => 0
if action == 1
    strategy.entry("Long", strategy.long)
if action == -1
    strategy.close("Long")
plot(sma3, "MA")
