//@version=5
strategy("GameStrat")
var int pos = 0
var float regretLong = 0.0
var float regretShort = 0.0
payLong = close - nz(close[1], close)
payShort = -payLong
regretLong := math.max(0.0, regretLong + payLong)
regretShort := math.max(0.0, regretShort + payShort)
totalReg = regretLong + regretShort
probLong = totalReg > 0.01 ? regretLong / totalReg : 0.5
if probLong > 0.65 and pos == 0
    strategy.entry("GL", strategy.long)
    pos := 1
else if probLong < 0.35 and pos == 1
    strategy.close("GL")
    pos := 0
plot(probLong, "PL")
