
//@version=5
indicator("Period State E")
enum PeriodState
    AllBull = 2
    TrendBull = 1
    Mixed = 0
    TrendBear = -1
    AllBear = -2

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
rsi = nz(ta.rsi(close, 3), 50.0)
ps = switch
    sma3 > sma5 and rsi > 55 and close > sma3 => PeriodState.AllBull
    sma3 > sma5 => PeriodState.TrendBull
    sma3 < sma5 and rsi < 45 and close < sma3 => PeriodState.AllBear
    sma3 < sma5 => PeriodState.TrendBear
    => PeriodState.Mixed
plot(int(ps), "PS")
