
//@version=5
indicator("Trade Sig E")
enum TradeSig
    StrongBuy = 2
    Buy = 1
    Hold = 0
    Sell = -1
    StrongSell = -2

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
rsi = nz(ta.rsi(close, 3), 50.0)
ts = switch
    sma3 > sma5 and rsi > 60 => TradeSig.StrongBuy
    sma3 > sma5 => TradeSig.Buy
    sma3 < sma5 and rsi < 40 => TradeSig.StrongSell
    sma3 < sma5 => TradeSig.Sell
    => TradeSig.Hold
plot(int(ts), "TS")
