
//@version=5
indicator("Reg Memory")
var int bullStreak = 0
var int bearStreak = 0
var int maxBullStreak = 0
var int maxBearStreak = 0
sma3 = ta.sma(close, 3)
if close > sma3
    bullStreak := bullStreak + 1
    bearStreak := 0
    maxBullStreak := math.max(maxBullStreak, bullStreak)
else
    bearStreak := bearStreak + 1
    bullStreak := 0
    maxBearStreak := math.max(maxBearStreak, bearStreak)
plot(maxBullStreak, "MBS")
