
//@version=5
indicator("Str Level")
enum StrLevel
    VeryStrong = 3
    Strong = 2
    Average = 1
    Weak = 0

rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
score = (close > sma3 ? 1 : 0) + (rsi > 55 ? 1 : 0) + (volume > ta.sma(volume, 5) ? 1 : 0)
sl = switch score
    3 => StrLevel.VeryStrong
    2 => StrLevel.Strong
    1 => StrLevel.Average
    => StrLevel.Weak
plot(int(sl), "SL")
