
//@version=5
indicator("Consensus")
rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
ema5 = ta.ema(close, 5)
[m, s, h] = ta.macd(close, 3, 5, 3)
k = ta.stoch(close, high, low, 5)
bullVotes = 0
if rsi > 50
    bullVotes := bullVotes + 1
if close > sma3
    bullVotes := bullVotes + 1
if sma3 > ema5
    bullVotes := bullVotes + 1
if h > 0
    bullVotes := bullVotes + 1
if k > 50
    bullVotes := bullVotes + 1
consensus = bullVotes >= 4 ? 1 : bullVotes <= 1 ? -1 : 0
plot(consensus, "Con")
