
//@version=5
indicator("Vol State")
var float maxATR = 0.0
var float minATR = 99999.0
var int regimeChanges = 0
var bool wasHighVol = false
atr = nz(ta.atr(3), 1.0)
avgATR = ta.sma(nz(ta.atr(3), 1.0), 5)
maxATR := math.max(maxATR, atr)
minATR := math.min(minATR, atr)
isHighVol = avgATR > 0 ? atr / avgATR > 1.3 : false
if isHighVol != wasHighVol
    regimeChanges := regimeChanges + 1
wasHighVol := isHighVol
plot(regimeChanges, "RC")
