
//@version=5
indicator("Zigzag")
var int direction = 0
var int zigzags = 0
var float lastPivot = close
threshold = ta.atr(3) * 0.5
if close > lastPivot + threshold and direction != 1
    direction := 1
    zigzags := zigzags + 1
    lastPivot := close
else if close < lastPivot - threshold and direction != -1
    direction := -1
    zigzags := zigzags + 1
    lastPivot := close
plot(zigzags, "Zigzags")
