
//@version=5
indicator("Enum Compare")
enum Phase
    Bull = 2
    Neutral = 0
    Bear = -2

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
phase = sma3 > sma5 ? Phase.Bull : sma3 < sma5 ? Phase.Bear : Phase.Neutral
var int lastPhase = 0
var int phaseChanges = 0
currentPhase = int(phase)
if currentPhase != lastPhase
    phaseChanges := phaseChanges + 1
lastPhase := currentPhase
plot(phaseChanges, "Changes")
