//@version=5
indicator("Squeeze")
length = 20
mult = 2.0
src = close
ma = ta.sma(src, length)
rangeMa = ta.sma(ta.tr, length)
upperBB = ma + mult * ta.stdev(src, length)
lowerBB = ma - mult * ta.stdev(src, length)
upperKC = ma + 1.5 * rangeMa
lowerKC = ma - 1.5 * rangeMa
sqzOn = lowerBB > lowerKC and upperBB < upperKC
sqzOff = lowerBB < lowerKC and upperBB > upperKC
noSqz = not sqzOn and not sqzOff
val = ta.linreg(src - (ta.highest(high, length) + ta.lowest(low, length)) / 2, length, 0)
plot(val)
