
//@version=5
indicator("Sess UDT")
type Session
    int barCount = 0
    float highVal = 0.0
    float lowVal = 99999.0

var Session sess = Session.new()
sess.barCount := sess.barCount + 1
sess.highVal := math.max(sess.highVal, high)
sess.lowVal := math.min(sess.lowVal, low)
if sess.barCount >= 5
    sess.barCount := 0
    sess.highVal := high
    sess.lowVal := low
plot(sess.highVal - sess.lowVal, "SR")
