//@version=5
indicator("CrossSinglePt")
p1 = array.new_float(0)
p2 = array.new_float(0)
child = array.new_float(0)
for i = 0 to 5
    array.push(p1, float(i) + close * 0.01)
    array.push(p2, float(5 - i) + close * 0.01)
crossPt = 3
for i = 0 to 5
    if i < crossPt
        array.push(child, array.get(p1, i))
    else
        array.push(child, array.get(p2, i))
plot(array.sum(child), "ChildSum")
