//@version=5
indicator("Squeeze")
var float result = 0.0
length = 5
bb_mult = 2.0
kc_mult = 1.5
basis = ta.sma(close, length)
dev_ = bb_mult * ta.stdev(close, length)
upperBB = basis + dev_
lowerBB = basis - dev_
ma = ta.sma(close, length)
range_ = ta.atr(length)
upperKC = ma + range_ * kc_mult
lowerKC = ma - range_ * kc_mult
sqzOn = lowerBB > lowerKC and upperBB < upperKC
result := sqzOn ? 1.0 : 0.0
