
//@version=5
indicator("Deep CF")
sma3 = ta.sma(close, 3)
rsi = nz(ta.rsi(close, 3), 50.0)
atr = nz(ta.atr(3), 1.0)
avgATR = ta.sma(nz(ta.atr(3), 1.0), 5)
result = 0
if close > sma3
    if rsi > 55
        if avgATR > 0 and atr / avgATR < 1.5
            result := 3
        else
            result := 2
    else
        result := 1
else
    if rsi < 45
        result := -2
    else
        result := -1
plot(result, "R")
