
//@version=5
indicator("AutoCorr")
var float[] prices = array.new_float(0)
array.push(prices, close)
if array.size(prices) > 8
    array.shift(prices)
n = array.size(prices)
corr = 0.0
if n > 2
    avg = array.avg(prices)
    numSum = 0.0
    denSum = 0.0
    for i = 0 to n - 2
        diff0 = array.get(prices, i) - avg
        diff1 = array.get(prices, i + 1) - avg
        numSum := numSum + diff0 * diff1
        denSum := denSum + diff0 * diff0
    corr := denSum > 0 ? numSum / denSum : 0.0
plot(corr, "AC")
