//@version=5
indicator("All Features")
// UDF
momentum(float src, int len) =>
    ta.sma(src, len) - ta.sma(src, len * 2)
// var
var float maxMom = 0.0
// array
var arr = array.new_float(0)
// calc
mom = momentum(close, 3)
// conditional update
if mom > maxMom and
    close > open
    maxMom := mom
// array ops
arr.push(mom)
if arr.size() > 5
    arr.shift()
// switch
signal = switch
    mom > 0 and close > ta.sma(close, 5) => 1
    mom < 0 and close < ta.sma(close, 5) => -1
    => 0
plot(signal)
