//@version=5
indicator("ATR", overlay=false)
length = input.int(14, title="Length")
smoothing = input.string("RMA", title="Smoothing", options=["RMA", "SMA", "EMA", "WMA"])
ma_function(source, length) =>
    if smoothing == "RMA"
        ta.rma(source, length)
    else if smoothing == "SMA"
        ta.sma(source, length)
    else if smoothing == "EMA"
        ta.ema(source, length)
    else
        ta.wma(source, length)
atr_val = ma_function(ta.tr, length)
plot(atr_val, title="ATR", color=color.yellow)
