
//@version=5
indicator("Trend Type")
enum TrendType
    StrongUp = 2
    WeakUp = 1
    Sideways = 0
    WeakDown = -1
    StrongDown = -2

rsi = nz(ta.rsi(close, 3), 50.0)
sma3 = ta.sma(close, 3)
tt = switch
    close > sma3 and rsi > 65 => TrendType.StrongUp
    close > sma3 => TrendType.WeakUp
    close < sma3 and rsi < 35 => TrendType.StrongDown
    close < sma3 => TrendType.WeakDown
    => TrendType.Sideways
plot(int(tt), "TT")
