//@version=5
indicator("Squeeze Momentum")
length = 5
mult = 2.0
sma_ = ta.sma(close, length)
dev_ = ta.stdev(close, length)
upperBB = sma_ + mult * dev_
lowerBB = sma_ - mult * dev_
atr_ = ta.atr(high, low, close, length)
upperKC = sma_ + 1.5 * atr_
lowerKC = sma_ - 1.5 * atr_
sqzOn = not na(lowerBB) and not na(lowerKC) and lowerBB > lowerKC and upperBB < upperKC
sqzOff = not na(lowerBB) and not na(lowerKC) and lowerBB < lowerKC and upperBB > upperKC
plot(sqzOn ? 1 : sqzOff ? -1 : 0)
