
//@version=5
indicator("MA State E")
enum MAState
    GoldenCross = 2
    Bullish = 1
    Neutral = 0
    Bearish = -1
    DeathCross = -2

sma3 = ta.sma(close, 3)
sma5 = ta.sma(close, 5)
st = switch
    ta.crossover(sma3, sma5) => MAState.GoldenCross
    sma3 > sma5 => MAState.Bullish
    ta.crossunder(sma3, sma5) => MAState.DeathCross
    sma3 < sma5 => MAState.Bearish
    => MAState.Neutral
plot(int(st), "St")
