
//@version=5
strategy("Enum Strat", overlay=true)
enum Signal
    StrongBuy = 2
    Buy = 1
    Hold = 0
    Sell = -1

sma3 = ta.sma(close, 3)
rsi = nz(ta.rsi(close, 3), 50.0)
sig = switch
    close > sma3 and rsi > 60 => Signal.StrongBuy
    close > sma3 => Signal.Buy
    rsi < 40 => Signal.Sell
    => Signal.Hold
if int(sig) >= 2
    strategy.entry("Long", strategy.long)
if int(sig) <= -1
    strategy.close("Long")
plot(sma3, "MA")
